 label=selected||v.label;if(!name||!label||!v.body){status('Identificador, texto do link e conteúdo são obrigatórios.','error');return}restore(false);const a=editor.selectionStart,b=editor.selectionEnd,src=editor.value,link='<a href=\"#'+escapeAttr(name)+'\">'+escapeAttr(label)+'</a>',ref='<tg-reference name=\"'+escapeAttr(name)+'\">'+escapeAttr(v.body)+'</tg-reference>';editor.value=src.slice(0,a)+link+src.slice(b)+(src.trim()?'\n\n':'')+ref;const pos=a+link.length;editor.focus();editor.setSelectionRange(pos,pos);savedSel={start:pos,end:pos};save();closePopover()})}
function detailsForm(){openForm('Detalhes',[['summary','Resumo','Obrigatório']],v=>{if(!v.summary){status('Informe o resumo do bloco.','error');return}wrapBlock('<details><summary>'+escapeAttr(v.summary)+'</summary>\n','\n</details>')})}
function mapForm(){openForm('Mapa',[['lat','Latitude','-23.5505'],['long','Longitude','-46.6333'],['zoom','Zoom','14']],v=>{if(!v.lat||!v.long){status('Latitude e longitude são obrigatórias.','error');return}replaceSelection('<tg-map lat="'+escapeAttr(v.lat)+'" long="'+escapeAttr(v.long)+'" zoom="'+escapeAttr(v.zoom||'14')+'"/>','',{cursorInside:false})})}
function buttonForm(type){const fields=type==='copy_text'?[['label','Texto do botão','Copiar'],['value','Texto copiado','']]:[['label','Texto do botão','Abrir'],['value','URL HTTPS','https://…']];openForm('Botão Rich 10.3',fields,v=>{if(type!=='copy_text'&&!/^https:\/\//i.test(v.value)){status('A URL do botão precisa usar HTTPS.','error');return}const attrs=type==='copy_text'?'type="copy_text" text="'+escapeAttr(v.value)+'"':'type="'+type+'" url="'+escapeAttr(v.value)+'"';wrapBlock('<tg-button-row align="center">\n<tg-button '+attrs+'>'+escapeAttr(v.label||'Abrir')+'</tg-button>\n','\n</tg-button-row>')})}
function renderPreview(){if(!editor.value.trim()){preview.innerHTML='<p style="color:var(--muted)">Nada para pré-visualizar.</p>';return}let md=editor.value.replace(/mdtxtrt:\/\/(?:photo|video|audio|voice|animation|document)\/([A-Za-z0-9_-]+)/g,'/media/$1').replace(/<tg-map[^>]*>/gi,'`[mapa Telegram]`').replace(/<tg-button-row[^>]*>|<\/tg-button-row>/gi,'').replace(/<tg-button[^>]*>(.*?)<\/tg-button>/gi,'[$1]').replace(/<tg-(?:collage|slideshow)[^>]*>|<\/tg-(?:collage|slideshow)>/gi,'').replace(/<blockquote expandable>/gi,'<blockquote>').replace(/<\/blockquote>/gi,'</blockquote>');try{preview.innerHTML='<div class="note">Prévia local. Telegram Rich 10.3 é a renderização definitiva.</div>'+marked.parse(md)}catch(e){preview.textContent=editor.value}}
function setView(v){view=v;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('on',b.dataset.view===v));editor.classList.toggle('on',v==='edit');preview.classList.toggle('on',v==='preview');closePopover();if(v==='preview')renderPreview();else editor.focus()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));setView('edit');
function openOptions(){remember();const b=document.getElementById('optionsBackdrop');b.classList.add('on');b.setAttribute('aria-hidden','false')}function closeSheets(){document.querySelectorAll('.sheetback').forEach(b=>{b.classList.remove('on');b.setAttribute('aria-hidden','true')})}document.getElementById('btnOptions').onclick=openOptions;document.querySelectorAll('[data-close-sheet]').forEach(b=>b.onclick=closeSheets);document.getElementById('optionsBackdrop').onclick=e=>{if(e.target===e.currentTarget)closeSheets()};
function loadFile(file){const reader=new FileReader();reader.onload=()=>{editor.value=String(reader.result||'').replace(/\r\n/g,'\n').replace(/\r/g,'\n');if(!inpTitle.value)inpTitle.value=(file.name||'').replace(/\.[^.]+$/,'');save();setView('edit');status('Markdown importado.','warn')};reader.readAsText(file)}document.getElementById('btnOpen').onclick=()=>{closeSheets();document.getElementById('file').click()};document.getElementById('file').onchange=e=>{if(e.target.files[0])loadFile(e.target.files[0]);e.target.value=''};
function initData(){return tg?String(tg.initData||'').trim():''}
async function api(endpoint){const data=initData(),headers={'Content-Type':'application/json'};if(data){headers.Authorization='tma '+data;headers['X-Telegram-Init-Data']=data}const r=await fetch(endpoint,{method:'POST',headers,body:JSON.stringify({init_data:data,title:inpTitle.value||'Sem título',content:editor.value})});const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)throw new Error(j.error||('HTTP '+r.status));return j}
async function deliver(action){const r=await fetch('/api/stash',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,title:inpTitle.value||'Sem título',content:editor.value})});const j=await r.json().catch(()=>({}));if(!r.ok||!j.url)throw new Error(j.error||('HTTP '+r.status));if(tg&&tg.openTelegramLink)tg.openTelegramLink(j.url);else location.href=j.url}
async function run(fn,label){if(busy)return;if(!editor.value.trim()){status('Documento vazio.','error');return}busy=true;status(label+'…','warn');try{await fn()}catch(err){status(err.message||'Falha não identificada.','error')}finally{busy=false}}
document.getElementById('btnChat').onclick=()=>run(async()=>{await deliver('chat');status('Conteúdo enviado ao bot para Telegram Rich 10.3.','warn')},'Enviando');document.getElementById('btnMd').onclick=()=>run(async()=>{await deliver('mdrich');status('Arquivo .md enviado ao bot.','warn')},'Exportando');document.getElementById('btnPub').onclick=()=>run(async()=>{const j=await api('/api/publish');let msg='Publicado: '+j.url;if(j.degradations&&j.degradations.length)msg+='\n\nAdaptações Telegraph:\n• '+j.degradations.join('\n• ');status(msg,j.degradations&&j.degradations.length?'warn':'');try{if(tg&&tg.openLink)tg.openLink(j.url);else window.open(j.url,'_blank')}catch(e){}},'Publicando');
})();
