laceSelection('$','$')],['Bloco',()=>wrapBlock('$$\n','\n$$')],['Bloco math',()=>wrapBlock('```math\n','\n```')]]},
 list:{title:'Lista',items:[['Marcadores',()=>prefixLines('- ')],['Numerada',()=>prefixLines('1. ')],['Tarefa',()=>prefixLines('- [ ] ')],['Tarefa concluída',()=>prefixLines('- [x] ')]]},
 media:{title:'Mídia',items:[['URL',()=>mediaUrlForm()],['Upload',()=>mediaUploadForm()],['Collage',()=>collectionForm('tg-collage')],['Slideshow',()=>collectionForm('tg-slideshow')]]},
 structure:{title:'Estrutura',items:[['Tabela',()=>tableForm()],['Referência',()=>referenceForm()],['Âncora',()=>openForm('Âncora',[['name','Nome','secao']],v=>replaceSelection('<a name="'+escapeAttr(v.name)+'"></a>','',{cursorInside:false}))],['Detalhes',()=>detailsForm()],['Mapa',()=>mapForm()],['Botão URL',()=>buttonForm('url')],['Botão copiar',()=>buttonForm('copy_text')],['Mini App',()=>buttonForm('web_app')],['Divisor',()=>wrapBlock('---','')],['Rodapé',()=>replaceSelection('<footer>','</footer>')]]}
};
function openMenu(key){remember();activeMenu=key;document.querySelectorAll('.tool').forEach(b=>b.classList.toggle('on',b.dataset.menu===key));popoverTitle.textContent=menus[key].title;popoverBody.innerHTML='';const grid=document.createElement('div');grid.className='grid';menus[key].items.forEach(([label,fn])=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('pointerdown',e=>e.preventDefault());b.onclick=fn;grid.appendChild(b)});popoverBody.appendChild(grid);popover.classList.add('on');popover.setAttribute('aria-hidden','false');positionPopover()}
function closePopover(){popover.classList.remove('on');popover.setAttribute('aria-hidden','true');document.querySelectorAll('.tool').forEach(b=>b.classList.remove('on'));activeMenu=''}
toolbar.querySelectorAll('[data-menu]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();remember()});b.onclick=()=>activeMenu===b.dataset.menu?closePopover():openMenu(b.dataset.menu)});document.getElementById('popoverClose').onclick=()=>{closePopover();restore()};
function escapeAttr(v){return String(v||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function openForm(title,fields,onSubmit,extra){remember();popoverTitle.textContent=title;popoverBody.innerHTML='';const f=document.createElement('form');f.className='form';fields.forEach(([name,label,placeholder,type])=>{const l=document.createElement('label');l.textContent=label;const i=document.createElement(type==='select'?'select':'input');i.name=name;if(type==='select'&&extra&&extra[name])extra[name].forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;i.appendChild(o)});else i.placeholder=placeholder||'';l.appendChild(i);f.appendChild(l)});const submit=document.createElement('button');submit.className='primary';submit.textContent='Aplicar';f.appendChild(submit);f.onsubmit=e=>{e.preventDefault();const vals={};fields.forEach(x=>vals[x[0]]=String(f.elements[x[0]].value||'').trim());onSubmit(vals)};popoverBody.appendChild(f);popover.classList.add('on');popover.setAttribute('aria-hidden','false');positionPopover()}
function mediaUrlForm(){openForm('Mídia Rich por URL',[['url','URL HTTPS','https://…'],['caption','Legenda','Opcional']],v=>{if(!/^https:\/\//i.test(v.url)){status('A mídia Rich por URL precisa usar HTTPS.','error');return}const cap=v.caption?' \"'+v.caption.replace(/\"/g,'')+'\"':'';wrapBlock('![]('+v.url+cap+')','')})}
let pendingMediaKind='auto';function mediaUploadForm(){openForm('Upload para Telegram',[['kind','Tipo','','select'],['caption','Legenda','Opcional']],v=>{pendingMediaKind=v.kind||'auto';document.getElementById('mediaFile').dataset.caption=v.caption||'';closePopover();document.getElementById('mediaFile').click()},{kind:[['auto','Automático'],['photo','Foto'],['video','Vídeo'],['animation','Animação'],['audio','Áudio'],['document','Documento']]})}
document.getElementById('mediaFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;const fd=new FormData();fd.append('file',file);fd.append('kind',pendingMediaKind);const auth=initData();if(auth)fd.append('init_data',auth);try{status('Enviando mídia…','warn');const r=await fetch('/api/media',{method:'POST',body:fd});const j=await r.json().catch(()=>({}));if(!r.ok||!j.id)throw new Error(j.error||('HTTP '+r.status));const cap=e.target.dataset.caption||'';const title=cap?' \"'+cap.replace(/\"/g,'')+'\"':'';restore(false);const s=editor.selectionStart,v=editor.value,tag='![](mdtxtrt://'+j.kind+'/'+j.id+title+')';editor.value=v.slice(0,s)+tag+v.slice(editor.selectionEnd);const p=s+tag.length;editor.focus();editor.setSelectionRange(p,p);savedSel={start:p,end:p};save();status('Mídia pronta para Telegram Rich 10.3.','warn')}catch(err){status(err.message||'Falha no upload.','error')}e.target.value=''};
function collectionForm(tag){openForm(tag==='tg-collage'?'Collage':'Slideshow',[['urls','URLs HTTPS separadas por espaço','https://… https://…']],v=>{const urls=v.urls.split(/\s+/).filter(Boolean);if(!urls.length||urls.some(u=>!/^https:\/\//i.test(u))){status('Informe URLs HTTPS válidas.','error');return}wrapBlock('<'+tag+'>\n\n'+urls.map(u=>'![]('+u+')').join('\n\n')+'\n\n','\n</'+tag+'>')})}
function tableForm(){openForm('Tabela',[['rows','Linhas','2'],['cols','Colunas','2']],v=>{let r=Math.max(1,Math.min(20,parseInt(v.rows||'2',10))),c=Math.max(1,Math.min(20,parseInt(v.cols||'2',10)));const blank='| '+Array(c).fill(' ').join(' | ')+' |',sep='| '+Array(c).fill('---').join(' | ')+' |';const rows=[blank,sep];for(let i=1;i<r;i++)rows.push(blank);wrapBlock(rows.join('\n'),'')})}
function referenceForm(){remember();const selected=editor.value.slice(savedSel.start,savedSel.end);openForm('Referência',[['name','Identificador','nota'],['label','Texto do link',selected?'Seleção atual':''],['body','Conteúdo da referência','']],v=>{const name=(v.name||'').replace(/[^A-Za-z0-9_.:-]/g,'-');const