(function(){
const tg=window.Telegram&&window.Telegram.WebApp?window.Telegram.WebApp:null;
const editor=document.getElementById('editor');
const titleInput=document.getElementById('inpTitle');
if(!editor)return;
const CACHE_KEY='mdtxtrt_draft',TITLE_KEY='mdtxtrt_title',META_KEY='mdtxtrt_draft_meta_v2';
let lastSent=null,saveTimer=null,lastSavedAtMs=null,saving=false,flushPromise=null,baseRevision=0;
let autosaveEl=document.getElementById('autosaveStatus');
if(!autosaveEl){autosaveEl=document.createElement('span');autosaveEl.id='autosaveStatus';autosaveEl.setAttribute('aria-live','polite');autosaveEl.style.cssText='grid-column:4;justify-self:end;max-width:42vw;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:10px;color:var(--muted);text-align:right';const brand=document.querySelector('.brand');if(brand)brand.appendChild(autosaveEl)}
function initData(){return tg?String(tg.initData||'').trim():''}
function state(){return{content:String(editor.value||''),title:titleInput?String(titleInput.value||''):''}}
function signature(value){return JSON.stringify([value.content,value.title])}
function readMeta(){try{const raw=localStorage.getItem(META_KEY);if(!raw)return null;const value=JSON.parse(raw);return value&&typeof value==='object'?value:null}catch(e){return null}}
function writeLocal(value,dirty){try{localStorage.setItem(CACHE_KEY,value.content);localStorage.setItem(TITLE_KEY,value.title);localStorage.setItem(META_KEY,JSON.stringify({dirty:!!dirty,base_revision:baseRevision,last_saved_at_ms:lastSavedAtMs||null}))}catch(e){}return value}
function stamp(ms){if(!ms)return'';const d=new Date(Number(ms)),now=new Date();const time=d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit'});if(d.toDateString()===now.toDateString())return time;return d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})+' '+time}
function responseTime(value){return Number(value&&value.updated_at_ms)||((Number(value&&value.updated_at)||0)*1000)||null}
function paintAutosave(){if(!autosaveEl)return;const pending=lastSent===null||signature(state())!==lastSent;if(saving){autosaveEl.textContent=lastSavedAtMs?'salvando… · saved '+stamp(lastSavedAtMs):'salvando…';return}if(lastSavedAtMs){autosaveEl.textContent=(pending?'alterado · saved ':'saved ')+stamp(lastSavedAtMs);return}autosaveEl.textContent=pending?'autosave pendente':'autosave aguardando'}
async function request(endpoint,payload,keepalive){const auth=initData();if(!auth)return null;const body=JSON.stringify(Object.assign({init_data:auth},payload||{}));const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'tma '+auth,'X-Telegram-Init-Data':auth},body,keepalive:!!keepalive});const json=await response.json().catch(()=>({}));if(!response.ok||json.ok===false){const error=new Error(json.error||('HTTP '+response.status));error.status=response.status;error.payload=json;throw error}return json}
async function flush(keepalive){let conflicts=0;while(true){const current=writeLocal(state(),true),sig=signature(current);if(sig===lastSent){writeLocal(current,false);break}saving=true;paintAutosave();try{const saved=await request('/api/draft/save',{content:current.content,title:current.title,base_revision:baseRevision},keepalive);if(!saved)break;baseRevision=Number(saved.revision)||0;lastSent=signature({content:String(saved.content||''),title:String(saved.title||'')});lastSavedAtMs=responseTime(saved)||Date.now();const latest=state(),dirty=signature(latest)!==lastSent;writeLocal(latest,dirty);if(!dirty)break;conflicts=0}catch(error){if(error.status===409&&error.payload&&error.payload.current&&conflicts<3){const remote=error.payload.current;baseRevision=Number(remote.revision)||0;lastSent=signature({content:String(remote.content||''),title:String(remote.title||'')});lastSavedAtMs=responseTime(remote)||lastSavedAtMs;writeLocal(state(),true);conflicts+=1;continue}console.warn('draft save',error);writeLocal(state(),true);break}}}
async function saveNow(keepalive){clearTimeout(saveTimer);const current=state(),sig=signature(current);writeLocal(current,sig!==lastSent);if(!initData()){paintAutosave();return null}if(sig===lastSent){writeLocal(current,false);paintAutosave();return null}if(flushPromise)return flushPromise;flushPromise=flush(!!keepalive).finally(()=>{saving=false;flushPromise=null;paintAutosave()});return flushPromise}
function scheduleSave(){clearTimeout(saveTimer);writeLocal(state(),true);paintAutosave();saveTimer=setTimeout(()=>saveNow(false),700)}
editor.addEventListener('input',scheduleSave);
if(titleInput)titleInput.addEventListener('input',scheduleSave);
setInterval(()=>{const current=state(),sig=signature(current);if(sig!==lastSent){writeLocal(current,true);scheduleSave()}else{writeLocal(current,false);paintAutosave()}},1200);
async function loadDraft(){const local=state(),meta=readMeta(),localDirty=meta?!!meta.dirty:!!(local.content||local.title);if(meta){baseRevision=Number(meta.base_revision)||0;lastSavedAtMs=Number(meta.last_saved_at_ms)||null}writeLocal(local,localDirty);if(!initData()){paintAutosave();return}try{const remote=await request('/api/draft/load',{},false);if(!remote)return;const remoteState={content:String(remote.content||''),title:String(remote.title||'')};baseRevision=Number(remote.revision)||0;lastSavedAtMs=responseTime(remote);lastSent=signature(remoteState);if(localDirty){writeLocal(local,true);paintAutosave();await saveNow(false);return}editor.value=remoteState.content;if(titleInput)titleInput.value=remoteState.title;writeLocal(remoteState,false);paintAutosave()}catch(error){console.warn('draft load',error);writeLocal(state(),true);paintAutosave()}}
window.addEventListener('pagehide',()=>{clearTimeout(saveTimer);saveNow(true)});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){clearTimeout(saveTimer);saveNow(true)}});
loadDraft();
})();
