import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
import {randomUUID} from 'node:crypto';
import {TextEncoder} from 'node:util';

const root = new URL('../', import.meta.url);
function page(tg){
  const dom = new JSDOM(readFileSync(new URL('index.html',root),'utf8'),{url:'https://mdtxtrt.up.railway.app/',runScripts:'outside-only'});
  const w = dom.window;
  w.matchMedia = () => ({matches:true,addEventListener(){}});
  w.TextEncoder = TextEncoder;
  Object.defineProperty(w.crypto,'randomUUID',{value:randomUUID});
  if(tg){w.Telegram={WebApp:{initData:'signed-payload',colorScheme:'dark',ready(){},expand(){},setHeaderColor(){},MainButton:{setText(){},show(){},onClick(){}},...tg}};w.fetch=tg.fetch;}
  w.eval(readFileSync(new URL('marked.js',root),'utf8'));
  w.eval(readFileSync(new URL('turndown.js',root),'utf8'));
  w.eval(readFileSync(new URL('app.js',root),'utf8'));
  return w;
}
test('editor starts and destination controls work',()=>{
  const w=page();
  assert.equal(w.document.querySelector('#destBtn').title,'Destino: Telegram');
  w.document.querySelector('#destBtn').click();
  assert.equal(w.document.querySelector('#destBtn').title,'Destino: Telegraph');
  w.close();
});
test('toolbar clicks edit selected text and undo and redo restore document states',()=>{
  const w=page(),d=w.document,editor=d.querySelector('#editor');
  editor.innerHTML='<p>texto selecionado</p>';
  editor.dispatchEvent(new w.Event('input',{bubbles:true}));
  const text=editor.querySelector('p').firstChild,range=d.createRange();
  range.setStart(text,0);range.setEnd(text,text.length);w.getSelection().removeAllRanges();w.getSelection().addRange(range);d.dispatchEvent(new w.Event('selectionchange'));
  d.querySelector('[data-cmd="bold"]').click();
  assert.equal(editor.querySelector('strong')?.textContent,'texto selecionado');
  d.querySelector('#undoBtn').click();
  assert.equal(editor.querySelector('strong'),null);
  assert.equal(editor.textContent,'texto selecionado');
  d.querySelector('#redoBtn').click();
  assert.equal(editor.querySelector('strong')?.textContent,'texto selecionado');
  w.close();
});
test('replace button changes text without removing semantic formatting',()=>{
  const w=page();
  w.document.querySelector('#editor').innerHTML='<p>Teste <strong>forte forte</strong></p>';
  w.document.querySelector('#findText').value='forte';
  w.document.querySelector('#replaceText').value='novo';
  w.document.querySelector('#replaceAll').click();
  assert.equal(w.document.querySelector('#editor strong').textContent,'novo novo');
  assert.equal(w.document.querySelector('#previewBtn'),null);
  assert.match(w.eval('buildRich().rich_message.html'),/<strong>novo novo<\/strong>/);
  w.close();
});
test('toolbar and insertion menu buttons produce the selected semantic blocks',()=>{
  const w=page(),d=w.document,e=d.querySelector('#editor');
  d.querySelector('#headingBtn').click();d.querySelector('#headingMenu [data-block="h3"]').click();
  assert.equal(d.body.contains(e),true);
  assert.ok(d.querySelector('#typebar'));
  assert.equal(e.firstElementChild?.tagName,'H3');
  d.querySelector('#plusBtn').click();d.querySelector('#plusMenu [data-insert="task"]').click();
  assert.equal(e.querySelector('input[type="checkbox"]')?.type,'checkbox');
  d.querySelector('#plusBtn').click();d.querySelector('#plusMenu [data-insert="ordered"]').click();
  assert.ok(e.querySelector('ol > li'));
  d.querySelector('#quoteBtn').click();d.querySelector('#quoteMenu [data-block="blockquote"]').click();
  assert.ok(e.querySelector('blockquote'));
  d.querySelector('#plusBtn').click();
  d.querySelector('#destBtn').click();
  assert.equal(d.body.dataset.destination,'telegraph');
  assert.equal(d.querySelector('#plusMenu [data-insert="task"]').hidden,true);
  assert.equal(d.querySelector('#plusMenu [data-insert="image"]').hidden,false);
  w.close();
});
test('find is under the app name and menu icons match their actions',()=>{
  const w=page();
  const d=w.document;
  d.querySelector('#brandBtn').click();
  assert.equal(d.querySelector('#importMenu').classList.contains('on'),true);
  d.querySelector('#findBtn').click();
  assert.equal(d.querySelector('#findMenu').classList.contains('on'),true);
  assert.equal(d.querySelector('#importMenu').classList.contains('on'),false);
  assert.deepEqual([...d.querySelectorAll('#findMenu .tools button')].map(el=>el.id),['findNext','replaceOne','replaceAll']);
  const items=[...d.querySelectorAll('#plusMenu button [data-icon]')].map(el=>el.dataset.icon);
  assert.equal(items.length,new Set(items).size);
  assert.equal(d.querySelector('#plusMenu [data-cmd="strike"] [data-icon]').dataset.icon,'strikethrough_s');
  assert.equal(d.querySelector('#plusMenu [data-insert="video"] [data-icon]').dataset.icon,'movie');
  w.close();
});
test('Markdown import, editor replacement and export retain supported structures',async()=>{
  const w=page(),d=w.document,editor=d.querySelector('#editor');
  let saved;
  w.URL.createObjectURL=blob=>(saved={blob},'blob:download');
  w.HTMLAnchorElement.prototype.click=function(){saved.name=this.download};
  const source='# Nome\n\n- [x] tarefa\n- [ ] próxima\n\n| A | B |\n| --- | --- |\n| 1 | 2 |\n\n**forte** e [site](https://example.com)';
  d.querySelector('#brandBtn').click();d.querySelector('#importMdBtn').click();
  assert.equal(d.querySelector('#fileInput').accept,'.md,text/markdown');
  Object.defineProperty(d.querySelector('#fileInput'),'files',{configurable:true,value:[{name:'source.md',text:async()=>source}]});
  d.querySelector('#fileInput').dispatchEvent(new w.Event('change'));
  await new Promise(resolve=>setTimeout(resolve,10));
  assert.equal(editor.querySelector('h1')?.textContent,'Nome');
  assert.equal(editor.querySelectorAll('input[type="checkbox"]').length,2);
  assert.equal(editor.querySelectorAll('table tr').length,2);
  assert.equal(editor.querySelector('strong')?.textContent,'forte');
  d.querySelector('#findText').value='tarefa';d.querySelector('#replaceText').value='feito';d.querySelector('#replaceAll').click();
  d.querySelector('#exportBtn').click();
  assert.equal(d.querySelector('#exportMenu').classList.contains('on'),true);
  d.querySelector('#exportMdBtn').click();
  await new Promise(resolve=>setTimeout(resolve,10));
  assert.equal(saved.name,'source.md');
  const output=await new Promise((resolve,reject)=>{const reader=new w.FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsText(saved.blob)});
  const again=w.eval('mdToBasicHTML('+JSON.stringify(output)+')');
  const round=w.document.createElement('div');round.innerHTML=again;
  assert.equal(round.querySelector('h1')?.textContent,'Nome');
  assert.equal(round.querySelectorAll('input[type="checkbox"]').length,2);
  assert.equal(round.querySelectorAll('table tr').length,2);
  assert.equal(round.querySelector('strong')?.textContent,'forte');
  assert.equal(round.querySelector('a')?.getAttribute('href'),'https://example.com');
  assert.match(round.textContent,/feito/);
  w.close();
});
test('TXT import stays literal and lossy export requires an explicit choice',async()=>{
  const w=page(),d=w.document;let saved,asked=0,allow=false;
  w.confirm=()=>{asked++;return allow};
  w.URL.createObjectURL=blob=>(saved={blob},'blob:download');
  w.HTMLAnchorElement.prototype.click=function(){saved.name=this.download};
  const source='literal <texto>\nlinha dois\n';
  Object.defineProperty(d.querySelector('#fileInput'),'files',{configurable:true,value:[{name:'texto.txt',text:async()=>source}]});
  d.querySelector('#fileInput').dispatchEvent(new w.Event('change'));
  await new Promise(resolve=>setTimeout(resolve,10));
  d.querySelector('#exportBtn').click();d.querySelector('#exportTxtBtn').click();
  await new Promise(resolve=>setTimeout(resolve,10));
  let output=await new Promise((resolve,reject)=>{const reader=new w.FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsText(saved.blob)});
  assert.equal(output,source);
  const editor=d.querySelector('#editor');editor.innerHTML='<p><strong>formato</strong></p>';
  d.querySelector('#exportTxtBtn').click();
  assert.equal(asked,1);
  allow=true;d.querySelector('#exportTxtBtn').click();
  await new Promise(resolve=>setTimeout(resolve,10));
  output=await new Promise((resolve,reject)=>{const reader=new w.FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsText(saved.blob)});
  assert.equal(output,'formato');
  w.close();
});
test('Telegram rich serializer rejects invalid elements and emits semantic message data',()=>{
  const w=page();
  const editor=w.document.querySelector('#editor');
  editor.innerHTML='<h2>Olá</h2><ul><li><input type="checkbox" checked>Feito</li></ul>';
  const msg=w.eval('buildRich()').rich_message;
  assert.equal(msg.html,'<h2>Olá</h2><ul><li><input type="checkbox" checked/>Feito</li></ul>');
  editor.innerHTML='<svg></svg>';
  assert.throws(()=>w.eval('buildRich()'),/não aceita/);
  w.close();
});
test('Mini App mode waits for backend initData validation',async()=>{
  let resolve;
  let fullscreen=0, hidden=0;
  const w=page({fetch:()=>new Promise(r=>resolve=r),requestFullscreen(){fullscreen++},MainButton:{hide(){hidden++}}});
  assert.equal(w.document.body.classList.contains('tg'),false);
  assert.equal(fullscreen,0);
  resolve({ok:true});
  await new Promise(r=>setTimeout(r,5));
  assert.equal(w.document.body.classList.contains('tg'),true);
  assert.equal(fullscreen,1);
  assert.equal(hidden,1);
  w.close();
});
test('Mini App export click publishes the current editor HTML to the authenticated endpoint',async()=>{
  const requests=[];
  const w=page({isFullscreen:true,fetch:async(url,options)=>{requests.push({url,options});return {ok:true,json:async()=>({via:'sendRichMessage'})}},requestFullscreen(){}});
  await new Promise(resolve=>setTimeout(resolve,5));
  w.document.querySelector('#editor').innerHTML='<p><strong>Texto enviado</strong></p>';
  w.document.querySelector('#exportBtn').click();
  await new Promise(resolve=>setTimeout(resolve,5));
  const send=requests.find(item=>item.url.endsWith('/api/telegram/send'));
  assert.ok(send);
  assert.equal(send.options.method,'POST');
  assert.deepEqual(JSON.parse(send.options.body),{initData:'signed-payload',html:'<p><strong>Texto enviado</strong></p>'});
  w.close();
});
test('Mini App destination switch publishes Telegraph nodes and retains the returned page path',async()=>{
  const requests=[];
  const w=page({isFullscreen:true,fetch:async(url,options)=>{requests.push({url,options});return {ok:true,json:async()=>({path:'owned-page',url:'https://telegra.ph/owned-page'})}},requestFullscreen(){},openLink(){}});
  await new Promise(resolve=>setTimeout(resolve,5));
  const d=w.document;d.querySelector('#docName').value='Documento';d.querySelector('#editor').innerHTML='<h3>Título</h3><p>Texto</p>';
  d.querySelector('#destBtn').click();d.querySelector('#exportBtn').click();
  await new Promise(resolve=>setTimeout(resolve,5));
  const publish=requests.find(item=>item.url.endsWith('/api/telegraph/publish'));
  assert.ok(publish);
  const data=JSON.parse(publish.options.body);
  assert.deepEqual(data.content,[{tag:'h3',children:['Título']},{tag:'p',children:['Texto']}]);
  assert.equal(data.title,'Documento');
  assert.equal(data.path,'');
  assert.equal(JSON.parse(w.localStorage.getItem('rmdtxtml')).telegraphPath,'owned-page');
  w.close();
});
test('fullscreen Mini App keeps menus below Telegram controls',async()=>{
  const w=page({fetch:async()=>({ok:true}),isFullscreen:true,safeAreaInset:{top:59,bottom:34},contentSafeAreaInset:{top:44,bottom:0}});
  await new Promise(r=>setTimeout(r,5));
  assert.equal(w.document.documentElement.style.getPropertyValue('--tg-top'),'111px');
  assert.equal(w.document.documentElement.style.getPropertyValue('--tg-bottom'),'34px');
  w.close();
});
test('Markdown preserves embeds and expandable quotes, rejects styles',()=>{
  const w=page();
  const html=w.eval('mdToBasicHTML("<figure><iframe src=\\\"https://example.com/\\\"></iframe></figure>\\n\\n<blockquote expandable>Mais</blockquote>")');
  assert.match(html,/<iframe/);
  assert.match(html,/data-expandable="true"/);
  w.document.querySelector('#editor').innerHTML=html;
  const md=w.eval('htmlToMarkdown(document.querySelector("#editor").innerHTML)');
  assert.match(md,/<iframe/);
  assert.match(md,/data-expandable/);
  assert.throws(()=>w.eval('mdToBasicHTML("<p style=\\\"color:red\\\">x</p>")'),/Atributo/);
  w.close();
});
test('local attachments cannot become unusable downloads',()=>{
  const w=page();
  const editor=w.document.querySelector('#editor');
  editor.innerHTML='<figure><img data-media-id="media1" src="blob:https://example.com/local"></figure>';
  assert.throws(()=>w.eval('htmlToMarkdown(document.querySelector("#editor").innerHTML)'),/URL pública/);
  assert.throws(()=>w.eval('htmlToText(document.querySelector("#editor").innerHTML)'),/TXT não comporta/);
  w.close();
});
test('insertions respect the caret between blocks',()=>{
  const w=page();
  const editor=w.document.querySelector('#editor');
  editor.innerHTML='<p>Antes</p><p>Depois</p>';
  const range=w.document.createRange();
  range.setStartAfter(editor.firstElementChild);range.collapse(true);
  w.getSelection().removeAllRanges();w.getSelection().addRange(range);
  w.eval('saveSel();insertFeature("divider")');
  assert.deepEqual([...editor.children].map(el=>el.tagName),['P','HR','P']);
  w.close();
});
test('block commands split paragraphs at the caret without nesting list and divider nodes',()=>{
  const w=page(),d=w.document,editor=d.querySelector('#editor');
  editor.innerHTML='<p>antes depois</p>';
  const text=editor.querySelector('p').firstChild,range=d.createRange();
  range.setStart(text,6);range.collapse(true);w.getSelection().removeAllRanges();w.getSelection().addRange(range);d.dispatchEvent(new w.Event('selectionchange'));
  d.querySelector('#plusBtn').click();d.querySelector('#plusMenu [data-insert="ordered"]').click();
  assert.deepEqual([...editor.children].map(node=>node.tagName),['P','OL','P']);
  assert.equal(editor.children[0].textContent,'antes ');
  assert.equal(editor.children[2].textContent,'depois');
  assert.equal(editor.querySelector('p ol'),null);
  w.close();
});
test('button insertion exposes only ready types and validates callback payload',()=>{
  const w=page();
  const editor=w.document.querySelector('#editor');
  w.prompt=()=> 'switch_inline_query';
  w.eval('insertFeature("button")');
  assert.equal(editor.querySelector('tg-button'),null);
  const answers=['callback_data','Abrir','link','ação'];
  w.prompt=()=>answers.shift();
  w.eval('insertFeature("button")');
  assert.equal(editor.querySelector('tg-button')?.getAttribute('data'),'ação');
  assert.match(w.eval('buildRich().rich_message.html'),/type="callback_data"/);
  const tooLong=['callback_data','Outro','primary','a'.repeat(65)];
  w.prompt=()=>tooLong.shift();
  w.eval('insertFeature("button")');
  assert.equal(editor.querySelectorAll('tg-button').length,1);
  w.close();
});
