export const S={
  dest:'telegram',
  session:'browser',
  busy:false,
  savedRange:null,
  editorCore:null,
  composing:false,
  saveTimer:null,
  remoteSaveTimer:null,
  remoteSaveQueue:Promise.resolve(),
  remoteMediaSyncedIds:new Set(),
  remoteSaveNoticeShown:false,
  telegraphPath:'',
  docId:crypto.randomUUID(),
  docRevision:0,
  docGeneration:0,
  importedMd:'',
  importedTxt:'',
  importedHtml:'',
  mediaFiles:new Map(),
  mediaChoice:null,
  draftWriteBlocked:false,
  draftBlockNoticeShown:false,
  activeHandoff:'',
  handoffAction:null,
  exportOverride:null,
  themePreference:'',
  dialogReturnFocus:null,
  dialogInerted:[],
  dialogResolve:null,
  dialogConfirm:false,
  dialogChoice:false,
  lastInteractionControl:null,
  viewportFrame:0,
  inset:0,
  caretFrame:0,
  draftRecoveryPending:false,
  
  deletingDoc:'',
  blankAfterDelete:'',
};
